package scanner_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ozgurcd/gograph/internal/scanner"
)

func TestShouldIgnoreDir(t *testing.T) {
	cases := []struct {
		dir    string
		expect bool
	}{
		{".git", true},
		{".gograph", true},
		{"vendor", true},
		{"node_modules", true},
		{"dist", true},
		{"build", true},
		{".terraform", true},
		{"internal", false},
		{"cmd", false},
		{"mypkg", false},
	}
	for _, tc := range cases {
		got := scanner.ShouldIgnoreDir(tc.dir)
		if got != tc.expect {
			t.Errorf("ShouldIgnoreDir(%q) = %v, want %v", tc.dir, got, tc.expect)
		}
	}
}

func TestShouldIgnoreFile_Suffixes(t *testing.T) {
	dir := t.TempDir()

	pb := filepath.Join(dir, "foo.pb.go")
	mustWrite(t, pb, "package foo\n")
	if skip, _ := scanner.ShouldIgnoreFile(pb); !skip {
		t.Error("expected .pb.go to be ignored")
	}

	gen := filepath.Join(dir, "bar_generated.go")
	mustWrite(t, gen, "package foo\n")
	if skip, _ := scanner.ShouldIgnoreFile(gen); !skip {
		t.Error("expected _generated.go to be ignored")
	}
}

func TestShouldIgnoreFile_CodeGeneratedComment(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "normal.go")
	mustWrite(t, path, "// Code generated by protoc. DO NOT EDIT.\npackage foo\n")
	if skip, _ := scanner.ShouldIgnoreFile(path); !skip {
		t.Error("expected file with 'Code generated' comment to be ignored")
	}
}

func TestShouldIgnoreFile_Normal(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "normal.go")
	mustWrite(t, path, "package foo\n\nfunc Hello() {}\n")
	if skip, _ := scanner.ShouldIgnoreFile(path); skip {
		t.Error("expected normal Go file not to be ignored")
	}
}

func TestWalk_SkipsIgnoredDirs(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "main.go"), "package main\nfunc main(){}\n")

	vendorDir := filepath.Join(root, "vendor", "pkg")
	if err := os.MkdirAll(vendorDir, 0o750); err != nil {
		t.Fatal(err)
	}
	mustWrite(t, filepath.Join(vendorDir, "vendor.go"), "package pkg\n")

	paths, errs := scanner.Walk(root)
	if len(errs) > 0 {
		t.Fatalf("unexpected errors: %v", errs)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 path, got %d: %v", len(paths), paths)
	}
}

func TestWalkWithOptions_IncludeGenerated(t *testing.T) {
	root := t.TempDir()

	// Normal file
	mustWrite(t, filepath.Join(root, "main.go"), "package main\nfunc main(){}\n")

	// .pb.go file
	mustWrite(t, filepath.Join(root, "foo.pb.go"), "package main\ntype Foo struct{}\n")

	// _generated.go file
	mustWrite(t, filepath.Join(root, "bar_generated.go"), "package main\ntype Bar struct{}\n")

	// File with Code generated comment
	mustWrite(t, filepath.Join(root, "baz.go"), "// Code generated by tool. DO NOT EDIT.\npackage main\ntype Baz struct{}\n")

	t.Run("default excludes generated", func(t *testing.T) {
		paths, errs := scanner.WalkWithOptions(root, scanner.Options{})
		if len(errs) > 0 {
			t.Fatalf("unexpected errors: %v", errs)
		}
		if len(paths) != 1 {
			t.Fatalf("expected 1 path (main.go only), got %d: %v", len(paths), paths)
		}
		if filepath.Base(paths[0]) != "main.go" {
			t.Errorf("expected main.go, got %s", paths[0])
		}
	})

	t.Run("include generated includes all files", func(t *testing.T) {
		paths, errs := scanner.WalkWithOptions(root, scanner.Options{IncludeGenerated: true})
		if len(errs) > 0 {
			t.Fatalf("unexpected errors: %v", errs)
		}
		if len(paths) != 4 {
			t.Fatalf("expected 4 paths (all .go files), got %d: %v", len(paths), paths)
		}
	})
}

func TestWalkWithOptions_IncludeGenerated_StillSkipsIgnoredDirs(t *testing.T) {
	root := t.TempDir()

	mustWrite(t, filepath.Join(root, "main.go"), "package main\nfunc main(){}\n")
	mustWrite(t, filepath.Join(root, "foo.pb.go"), "package main\ntype Foo struct{}\n")

	// vendor dir should still be skipped even with IncludeGenerated
	vendorDir := filepath.Join(root, "vendor", "pkg")
	if err := os.MkdirAll(vendorDir, 0o750); err != nil {
		t.Fatal(err)
	}
	mustWrite(t, filepath.Join(vendorDir, "vendor.go"), "package pkg\n")
	mustWrite(t, filepath.Join(vendorDir, "gen.pb.go"), "package pkg\n")

	paths, errs := scanner.WalkWithOptions(root, scanner.Options{IncludeGenerated: true})
	if len(errs) > 0 {
		t.Fatalf("unexpected errors: %v", errs)
	}
	if len(paths) != 2 {
		t.Fatalf("expected 2 paths (main.go + foo.pb.go), got %d: %v", len(paths), paths)
	}
}

func TestWalk_BackwardCompatible(t *testing.T) {
	// Walk() without options should still exclude generated files (backward compat)
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "main.go"), "package main\nfunc main(){}\n")
	mustWrite(t, filepath.Join(root, "foo.pb.go"), "package main\ntype Foo struct{}\n")

	paths, errs := scanner.Walk(root)
	if len(errs) > 0 {
		t.Fatalf("unexpected errors: %v", errs)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 path, got %d: %v", len(paths), paths)
	}
	if filepath.Base(paths[0]) != "main.go" {
		t.Errorf("expected main.go, got %s", paths[0])
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o640); err != nil {
		t.Fatal(err)
	}
}
